#ifndef DALI_CONFIG_H_
#define DALI_CONFIG_H_

#include <stm32f10x.h>

#define BUS_COUNT 7
#define MAX_BUS_DEVICES_COUNT 64
#define ALL_DEVICE_COUNT BUS_COUNT *MAX_BUS_DEVICES_COUNT

#define BUS0_PORT_RX GPIOC
#define BUS0_PORT_NO_RX 14
#define BUS0_PORT_TX GPIOC
#define BUS0_PORT_NO_TX 15
#define BUS0_PORT_ENA GPIOB
#define BUS0_PORT_NO_ENA 9

#define BUS1_PORT_RX GPIOA
#define BUS1_PORT_NO_RX 0
#define BUS1_PORT_TX GPIOA
#define BUS1_PORT_NO_TX 1
#define BUS1_PORT_ENA GPIOB
#define BUS1_PORT_NO_ENA 8

#define BUS2_PORT_RX GPIOA
#define BUS2_PORT_NO_RX 2
#define BUS2_PORT_TX GPIOA
#define BUS2_PORT_NO_TX 3
#define BUS2_PORT_ENA GPIOB
#define BUS2_PORT_NO_ENA 7

#define BUS3_PORT_RX GPIOA
#define BUS3_PORT_NO_RX 4
#define BUS3_PORT_TX GPIOA
#define BUS3_PORT_NO_TX 5
#define BUS3_PORT_ENA GPIOB
#define BUS3_PORT_NO_ENA 6

#define BUS4_PORT_RX GPIOA
#define BUS4_PORT_NO_RX 6
#define BUS4_PORT_TX GPIOA
#define BUS4_PORT_NO_TX 7
#define BUS4_PORT_ENA GPIOB
#define BUS4_PORT_NO_ENA 5

#define BUS5_PORT_RX GPIOB
#define BUS5_PORT_NO_RX 1
#define BUS5_PORT_TX GPIOB
#define BUS5_PORT_NO_TX 0
#define BUS5_PORT_ENA GPIOB
#define BUS5_PORT_NO_ENA 2

#define BUS6_PORT_RX GPIOB
#define BUS6_PORT_NO_RX 3
#define BUS6_PORT_TX GPIOA
#define BUS6_PORT_NO_TX 15
#define BUS6_PORT_ENA GPIOB
#define BUS6_PORT_NO_ENA 4

const static struct
{
	GPIO_TypeDef *tx_port;
	GPIO_TypeDef *rx_port;
	GPIO_TypeDef *ena_port;
	uint8_t tx_port_no;
	uint8_t rx_port_no;
	uint8_t ena_port_no;
} BUS_MAP[BUS_COUNT] =
	{
		{BUS0_PORT_TX, BUS0_PORT_RX, BUS0_PORT_ENA, BUS0_PORT_NO_TX, BUS0_PORT_NO_RX, BUS0_PORT_NO_ENA},
		{BUS1_PORT_TX, BUS1_PORT_RX, BUS1_PORT_ENA, BUS1_PORT_NO_TX, BUS1_PORT_NO_RX, BUS1_PORT_NO_ENA},
		{BUS2_PORT_TX, BUS2_PORT_RX, BUS2_PORT_ENA, BUS2_PORT_NO_TX, BUS2_PORT_NO_RX, BUS2_PORT_NO_ENA},
		{BUS3_PORT_TX, BUS3_PORT_RX, BUS3_PORT_ENA, BUS3_PORT_NO_TX, BUS3_PORT_NO_RX, BUS3_PORT_NO_ENA},
		{BUS4_PORT_TX, BUS4_PORT_RX, BUS4_PORT_ENA, BUS4_PORT_NO_TX, BUS4_PORT_NO_RX, BUS4_PORT_NO_ENA},
		{BUS5_PORT_TX, BUS5_PORT_RX, BUS5_PORT_ENA, BUS5_PORT_NO_TX, BUS5_PORT_NO_RX, BUS5_PORT_NO_ENA},
		{BUS6_PORT_TX, BUS6_PORT_RX, BUS6_PORT_ENA, BUS6_PORT_NO_TX, BUS6_PORT_NO_RX, BUS6_PORT_NO_ENA}};

#endif /* DALI_CONFIG_H_ */
